<template>
    <button
        class="
            bg-base-gray-2
            shadow-base
            active:shadow-base-active
            disabled:opacity-30
        "
        type="button"
    >
        <slot/>
    </button>
</template>